import Foundation
import CoreBluetooth

let CharacteristicUUIDDescriptions: [CBUUID : String] = [
    CBUUID(string: "0x2A00") : "Device Name",
    CBUUID(string: "0x2A01") : "Appearance",
    CBUUID(string: "0x2A02") : "Peripheral Privacy Flag",
    CBUUID(string: "0x2A03") : "Reconnection Address",
    CBUUID(string: "0x2A04") : "Peripheral Preferred Connection Parameters",
    CBUUID(string: "0x2A05") : "Service Changed",
    CBUUID(string: "0x2A06") : "Alert Level",
    CBUUID(string: "0x2A07") : "Tx Power Level",
    CBUUID(string: "0x2A08") : "Date Time",
    CBUUID(string: "0x2A09") : "Day of Week",
    CBUUID(string: "0x2A0A") : "Day Date Time",
    CBUUID(string: "0x2A0C") : "Exact Time 256",
    CBUUID(string: "0x2A0D") : "DST Offset",
    CBUUID(string: "0x2A0E") : "Time Zone",
    CBUUID(string: "0x2A0F") : "Local Time Information",
    CBUUID(string: "0x2A11") : "Time with DST",
    CBUUID(string: "0x2A12") : "Time Accuracy",
    CBUUID(string: "0x2A13") : "Time Source",
    CBUUID(string: "0x2A14") : "Reference Time Information",
    CBUUID(string: "0x2A16") : "Time Update Control Point",
    CBUUID(string: "0x2A17") : "Time Update State",
    CBUUID(string: "0x2A18") : "Glucose Measurement",
    CBUUID(string: "0x2A19") : "Battery Level",
    CBUUID(string: "0x2A1C") : "Temperature Measurement",
    CBUUID(string: "0x2A1D") : "Temperature Type",
    CBUUID(string: "0x2A1E") : "Intermediate Temperature",
    CBUUID(string: "0x2A21") : "Measurement Interval",
    CBUUID(string: "0x2A22") : "Boot Keyboard Input Report",
    CBUUID(string: "0x2A23") : "System ID",
    CBUUID(string: "0x2A24") : "Model Number",
    CBUUID(string: "0x2A25") : "Serial Number",
    CBUUID(string: "0x2A26") : "Firmware Revision",
    CBUUID(string: "0x2A27") : "Hardware Revision",
    CBUUID(string: "0x2A28") : "Software Revision",
    CBUUID(string: "0x2A29") : "Manufacturer Name",
    CBUUID(string: "0x2A2A") : "IEEE 11073-20601 Regulatory Certification Data List",
    CBUUID(string: "0x2A2B") : "Current Time",
    CBUUID(string: "0x2A2C") : "Magnetic Declination",
    CBUUID(string: "0x2A31") : "Scan Refresh",
    CBUUID(string: "0x2A32") : "Boot Keyboard Output Report",
    CBUUID(string: "0x2A33") : "Boot Mouse Input Report",
    CBUUID(string: "0x2A34") : "Glucose Measurement Context",
    CBUUID(string: "0x2A35") : "Blood Pressure Measurement",
    CBUUID(string: "0x2A36") : "Intermediate Cuff Pressure",
    CBUUID(string: "0x2A37") : "Heart Rate Measurement",
    CBUUID(string: "0x2A38") : "Body Sensor Location",
    CBUUID(string: "0x2A39") : "Heart Rate Control Point",
    CBUUID(string: "0x2A3F") : "Alert Status",
    CBUUID(string: "0x2A40") : "Ringer Control Point",
    CBUUID(string: "0x2A41") : "Ringer Setting",
    CBUUID(string: "0x2A42") : "Alert Category ID Bit Mask",
    CBUUID(string: "0x2A43") : "Alert Category ID",
    CBUUID(string: "0x2A44") : "Alert Notification Control Point",
    CBUUID(string: "0x2A45") : "Unread Alert Status",
    CBUUID(string: "0x2A46") : "New Alert",
    CBUUID(string: "0x2A47") : "Supported New Alert Category",
    CBUUID(string: "0x2A48") : "Supported Unread Alert Category",
    CBUUID(string: "0x2A49") : "Blood Pressure Feature",
    CBUUID(string: "0x2A4A") : "HID Information",
    CBUUID(string: "0x2A4B") : "Report Map",
    CBUUID(string: "0x2A4C") : "HID Control Point",
    CBUUID(string: "0x2A4D") : "Report",
    CBUUID(string: "0x2A4E") : "Protocol Mode",
    CBUUID(string: "0x2A4F") : "Scan Interval Window",
    CBUUID(string: "0x2A50") : "PnP ID",
    CBUUID(string: "0x2A51") : "Glucose Feature",
    CBUUID(string: "0x2A52") : "Record Access Control Point",
    CBUUID(string: "0x2A53") : "RSC Measurement",
    CBUUID(string: "0x2A54") : "RSC Feature",
    CBUUID(string: "0x2A55") : "SC Control Point",
    CBUUID(string: "0x2A5A") : "Aggregate",
    CBUUID(string: "0x2A5B") : "CSC Measurement",
    CBUUID(string: "0x2A5C") : "CSC Feature",
    CBUUID(string: "0x2A5D") : "Sensor Location",
    CBUUID(string: "0x2A5E") : "PLX Spot-Check Measurement",
    CBUUID(string: "0x2A5F") : "PLX Continuous Measurement",
    CBUUID(string: "0x2A60") : "PLX Features",
    CBUUID(string: "0x2A63") : "Cycling Power Measurement",
    CBUUID(string: "0x2A64") : "Cycling Power Vector",
    CBUUID(string: "0x2A65") : "Cycling Power Feature",
    CBUUID(string: "0x2A66") : "Cycling Power Control Point",
    CBUUID(string: "0x2A67") : "Location and Speed",
    CBUUID(string: "0x2A68") : "Navigation",
    CBUUID(string: "0x2A69") : "Position Quality",
    CBUUID(string: "0x2A6A") : "LN Feature",
    CBUUID(string: "0x2A6B") : "LN Control Point",
    CBUUID(string: "0x2A6C") : "Elevation",
    CBUUID(string: "0x2A6D") : "Pressure",
    CBUUID(string: "0x2A6E") : "Temperature",
    CBUUID(string: "0x2A6F") : "Humidity",
    CBUUID(string: "0x2A70") : "True Wind Speed",
    CBUUID(string: "0x2A71") : "True Wind Direction",
    CBUUID(string: "0x2A72") : "Apparent Wind Speed",
    CBUUID(string: "0x2A73") : "Apparent Wind Direction",
    CBUUID(string: "0x2A74") : "Gust Factor",
    CBUUID(string: "0x2A75") : "Pollen Concentration",
    CBUUID(string: "0x2A76") : "UV Index",
    CBUUID(string: "0x2A77") : "Irradiance",
    CBUUID(string: "0x2A78") : "Rainfall",
    CBUUID(string: "0x2A79") : "Wind Chill",
    CBUUID(string: "0x2A7A") : "Heat Index",
    CBUUID(string: "0x2A7B") : "Dew Point",
    CBUUID(string: "0x2A7D") : "Descriptor Value Changed",
    CBUUID(string: "0x2A7E") : "Aerobic Heart Rate Lower Limit",
    CBUUID(string: "0x2A7F") : "Aerobic Threshold",
    CBUUID(string: "0x2A80") : "Age",
    CBUUID(string: "0x2A81") : "Anaerobic Heart Rate Lower Limit",
    CBUUID(string: "0x2A82") : "Anaerobic Heart Rate Upper Limit",
    CBUUID(string: "0x2A83") : "Anaerobic Threshold",
    CBUUID(string: "0x2A84") : "Aerobic Heart Rate Upper Limit",
    CBUUID(string: "0x2A85") : "Date of Birth",
    CBUUID(string: "0x2A86") : "Date of Threshold Assessment",
    CBUUID(string: "0x2A87") : "Email Address",
    CBUUID(string: "0x2A88") : "Fat Burn Heart Rate Lower Limit",
    CBUUID(string: "0x2A89") : "Fat Burn Heart Rate Upper Limit",
    CBUUID(string: "0x2A8A") : "First Name",
    CBUUID(string: "0x2A8B") : "Five Zone Heart Rate Limits",
    CBUUID(string: "0x2A8C") : "Gender",
    CBUUID(string: "0x2A8D") : "Heart Rate Max",
    CBUUID(string: "0x2A8E") : "Height",
    CBUUID(string: "0x2A8F") : "Hip Circumference",
    CBUUID(string: "0x2A90") : "Last Name",
    CBUUID(string: "0x2A91") : "Maximum Recommended Heart Rate",
    CBUUID(string: "0x2A92") : "Resting Heart Rate",
    CBUUID(string: "0x2A93") : "Sport Type for Aerobic and Anaerobic Thresholds",
    CBUUID(string: "0x2A94") : "Three Zone Heart Rate Limits",
    CBUUID(string: "0x2A95") : "Two Zone Heart Rate Limits",
    CBUUID(string: "0x2A96") : "VO2 Max",
    CBUUID(string: "0x2A97") : "Waist Circumference",
    CBUUID(string: "0x2A98") : "Weight",
    CBUUID(string: "0x2A99") : "Database Change Increment",
    CBUUID(string: "0x2A9A") : "User Index",
    CBUUID(string: "0x2A9B") : "Body Composition Feature",
    CBUUID(string: "0x2A9C") : "Body Composition Measurement",
    CBUUID(string: "0x2A9D") : "Weight Measurement",
    CBUUID(string: "0x2A9E") : "Weight Scale Feature",
    CBUUID(string: "0x2A9F") : "User Control Point",
    CBUUID(string: "0x2AA0") : "Magnetic Flux Density - 2D",
    CBUUID(string: "0x2AA1") : "Magnetic Flux Density - 3D",
    CBUUID(string: "0x2AA2") : "Language",
    CBUUID(string: "0x2AA3") : "Barometric Pressure Trend",
    CBUUID(string: "0x2AA4") : "Bond Management Control Point",
    CBUUID(string: "0x2AA5") : "Bond Management Feature",
    CBUUID(string: "0x2AA6") : "Central Address Resolution",
    CBUUID(string: "0x2AA7") : "CGM Measurement",
    CBUUID(string: "0x2AA8") : "CGM Feature",
    CBUUID(string: "0x2AA9") : "CGM Status",
    CBUUID(string: "0x2AAA") : "CGM Session Start Time",
    CBUUID(string: "0x2AAB") : "CGM Session Run Time",
    CBUUID(string: "0x2AAC") : "CGM Specific Ops Control Point",
    CBUUID(string: "0x2AAD") : "Indoor Positioning Configuration",
    CBUUID(string: "0x2AAE") : "Latitude",
    CBUUID(string: "0x2AAF") : "Longitude",
    CBUUID(string: "0x2AB0") : "Local North Coordinate",
    CBUUID(string: "0x2AB1") : "Local East Coordinate",
    CBUUID(string: "0x2AB2") : "Floor Number",
    CBUUID(string: "0x2AB3") : "Altitude",
    CBUUID(string: "0x2AB4") : "Uncertainty",
    CBUUID(string: "0x2AB5") : "Location Name",
    CBUUID(string: "0x2AB6") : "URI",
    CBUUID(string: "0x2AB7") : "HTTP Headers",
    CBUUID(string: "0x2AB8") : "HTTP Status Code",
    CBUUID(string: "0x2AB9") : "HTTP Entity Body",
    CBUUID(string: "0x2ABA") : "HTTP Control Point",
    CBUUID(string: "0x2ABB") : "HTTPS Security",
    CBUUID(string: "0x2ABC") : "TDS Control Point",
    CBUUID(string: "0x2ABD") : "OTS Feature",
    CBUUID(string: "0x2ABE") : "Object Name",
    CBUUID(string: "0x2ABF") : "Object Type",
    CBUUID(string: "0x2AC0") : "Object Size",
    CBUUID(string: "0x2AC1") : "Object First-Created",
    CBUUID(string: "0x2AC2") : "Object Last-Modified",
    CBUUID(string: "0x2AC3") : "Object ID",
    CBUUID(string: "0x2AC4") : "Object Properties",
    CBUUID(string: "0x2AC5") : "Object Action Control Point",
    CBUUID(string: "0x2AC6") : "Object List Control Point",
    CBUUID(string: "0x2AC7") : "Object List Filter",
    CBUUID(string: "0x2AC8") : "Object Changed",
    CBUUID(string: "0x2AC9") : "Resolvable Private Address Only",
    CBUUID(string: "0x2ACC") : "Fitness Machine Feature",
    CBUUID(string: "0x2ACD") : "Treadmill Data",
    CBUUID(string: "0x2ACE") : "Cross Trainer Data",
    CBUUID(string: "0x2ACF") : "Step Climber Data",
    CBUUID(string: "0x2AD0") : "Stair Climber Data",
    CBUUID(string: "0x2AD1") : "Rower Data",
    CBUUID(string: "0x2AD2") : "Indoor Bike Data",
    CBUUID(string: "0x2AD3") : "Training Status",
    CBUUID(string: "0x2AD4") : "Supported Speed Range",
    CBUUID(string: "0x2AD5") : "Supported Inclination Range",
    CBUUID(string: "0x2AD6") : "Supported Resistance Level Range",
    CBUUID(string: "0x2AD7") : "Supported Heart Rate Range",
    CBUUID(string: "0x2AD8") : "Supported Power Range",
    CBUUID(string: "0x2AD9") : "Fitness Machine Control Point",
    CBUUID(string: "0x2ADA") : "Fitness Machine Status",
    CBUUID(string: "0x2ADB") : "Mesh Provisioning Data In",
    CBUUID(string: "0x2ADC") : "Mesh Provisioning Data Out",
    CBUUID(string: "0x2ADD") : "Mesh Proxy Data In",
    CBUUID(string: "0x2ADE") : "Mesh Proxy Data Out",
    CBUUID(string: "0x2AE0") : "Average Current",
    CBUUID(string: "0x2AE1") : "Average Voltage",
    CBUUID(string: "0x2AE2") : "Boolean",
    CBUUID(string: "0x2AE3") : "Chromatic Distance from Planckian",
    CBUUID(string: "0x2AE4") : "Chromaticity Coordinates",
    CBUUID(string: "0x2AE5") : "Chromaticity in CCT and Duv Values",
    CBUUID(string: "0x2AE6") : "Chromaticity Tolerance",
    CBUUID(string: "0x2AE7") : "CIE 13.3-1995 Color Rendering Index",
    CBUUID(string: "0x2AE8") : "Coefficient",
    CBUUID(string: "0x2AE9") : "Correlated Color Temperature",
    CBUUID(string: "0x2AEA") : "Count 16",
    CBUUID(string: "0x2AEB") : "Count 24",
    CBUUID(string: "0x2AEC") : "Country Code",
    CBUUID(string: "0x2AED") : "Date UTC",
    CBUUID(string: "0x2AEE") : "Electric Current",
    CBUUID(string: "0x2AEF") : "Electric Current Range",
    CBUUID(string: "0x2AF0") : "Electric Current Specification",
    CBUUID(string: "0x2AF1") : "Electric Current Statistics",
    CBUUID(string: "0x2AF2") : "Energy",
    CBUUID(string: "0x2AF3") : "Energy in a Period of Day",
    CBUUID(string: "0x2AF4") : "Event Statistics",
    CBUUID(string: "0x2AF5") : "Fixed String 16",
    CBUUID(string: "0x2AF6") : "Fixed String 24",
    CBUUID(string: "0x2AF7") : "Fixed String 36",
    CBUUID(string: "0x2AF8") : "Fixed String 8",
    CBUUID(string: "0x2AF9") : "Generic Level",
    CBUUID(string: "0x2AFA") : "Global Trade Item Number",
    CBUUID(string: "0x2AFB") : "Illuminance",
    CBUUID(string: "0x2AFC") : "Luminous Efficacy",
    CBUUID(string: "0x2AFD") : "Luminous Energy",
    CBUUID(string: "0x2AFE") : "Luminous Exposure",
    CBUUID(string: "0x2AFF") : "Luminous Flux",
    CBUUID(string: "0x2B00") : "Luminous Flux Range",
    CBUUID(string: "0x2B01") : "Luminous Intensity",
    CBUUID(string: "0x2B02") : "Mass Flow",
    CBUUID(string: "0x2B03") : "Perceived Lightness",
    CBUUID(string: "0x2B04") : "Percentage 8",
    CBUUID(string: "0x2B05") : "Power",
    CBUUID(string: "0x2B06") : "Power Specification",
    CBUUID(string: "0x2B07") : "Relative Runtime in a Current Range",
    CBUUID(string: "0x2B08") : "Relative Runtime in a Generic Level Range",
    CBUUID(string: "0x2B09") : "Relative Value in a Voltage Range",
    CBUUID(string: "0x2B0A") : "Relative Value in an Illuminance Range",
    CBUUID(string: "0x2B0B") : "Relative Value in a Period of Day",
    CBUUID(string: "0x2B0C") : "Relative Value in a Temperature Range",
    CBUUID(string: "0x2B0D") : "Temperature 8",
    CBUUID(string: "0x2B0E") : "Temperature 8 in a Period of Day",
    CBUUID(string: "0x2B0F") : "Temperature 8 Statistics",
    CBUUID(string: "0x2B10") : "Temperature Range",
    CBUUID(string: "0x2B11") : "Temperature Statistics",
    CBUUID(string: "0x2B12") : "Time Decihour 8",
    CBUUID(string: "0x2B13") : "Time Exponential 8",
    CBUUID(string: "0x2B14") : "Time Hour 24",
    CBUUID(string: "0x2B15") : "Time Millisecond 24",
    CBUUID(string: "0x2B16") : "Time Second 16",
    CBUUID(string: "0x2B17") : "Time Second 8",
    CBUUID(string: "0x2B18") : "Voltage",
    CBUUID(string: "0x2B19") : "Voltage Specification",
    CBUUID(string: "0x2B1A") : "Voltage Statistics",
    CBUUID(string: "0x2B1B") : "Volume Flow",
    CBUUID(string: "0x2B1C") : "Chromaticity Coordinate",
    CBUUID(string: "0x2B1D") : "RC Feature",
    CBUUID(string: "0x2B1E") : "RC Settings",
    CBUUID(string: "0x2B1F") : "Reconnection Configuration Control Point",
    CBUUID(string: "0x2B20") : "IDD Status Changed",
    CBUUID(string: "0x2B21") : "IDD Status",
    CBUUID(string: "0x2B22") : "IDD Annunciation Status",
    CBUUID(string: "0x2B23") : "IDD Features",
    CBUUID(string: "0x2B24") : "IDD Status Reader Control Point",
    CBUUID(string: "0x2B25") : "IDD Command Control Point",
    CBUUID(string: "0x2B26") : "IDD Command Data",
    CBUUID(string: "0x2B27") : "IDD Record Access Control Point",
    CBUUID(string: "0x2B28") : "IDD History Data",
    CBUUID(string: "0x2B29") : "Client Supported Features",
    CBUUID(string: "0x2B2A") : "Database Hash",
    CBUUID(string: "0x2B2B") : "BSS Control Point",
    CBUUID(string: "0x2B2C") : "BSS Response",
    CBUUID(string: "0x2B2D") : "Emergency ID",
    CBUUID(string: "0x2B2E") : "Emergency Text",
    CBUUID(string: "0x2B2F") : "ACS Status",
    CBUUID(string: "0x2B30") : "ACS Data In",
    CBUUID(string: "0x2B31") : "ACS Data Out Notify",
    CBUUID(string: "0x2B32") : "ACS Data Out Indicate",
    CBUUID(string: "0x2B33") : "ACS Control Point",
    CBUUID(string: "0x2B34") : "Enhanced Blood Pressure Measurement",
    CBUUID(string: "0x2B35") : "Enhanced Intermediate Cuff Pressure",
    CBUUID(string: "0x2B36") : "Blood Pressure Record",
    CBUUID(string: "0x2B37") : "Registered User",
    CBUUID(string: "0x2B38") : "BR-EDR Handover Data",
    CBUUID(string: "0x2B39") : "Bluetooth SIG Data",
    CBUUID(string: "0x2B3A") : "Server Supported Features",
    CBUUID(string: "0x2B3B") : "Physical Activity Monitor Features",
    CBUUID(string: "0x2B3C") : "General Activity Instantaneous Data",
    CBUUID(string: "0x2B3D") : "General Activity Summary Data",
    CBUUID(string: "0x2B3E") : "CardioRespiratory Activity Instantaneous Data",
    CBUUID(string: "0x2B3F") : "CardioRespiratory Activity Summary Data",
    CBUUID(string: "0x2B40") : "Step Counter Activity Summary Data",
    CBUUID(string: "0x2B41") : "Sleep Activity Instantaneous Data",
    CBUUID(string: "0x2B42") : "Sleep Activity Summary Data",
    CBUUID(string: "0x2B43") : "Physical Activity Monitor Control Point",
    CBUUID(string: "0x2B44") : "Physical Activity Current Session",
    CBUUID(string: "0x2B45") : "Physical Activity Session Descriptor",
    CBUUID(string: "0x2B46") : "Preferred Units",
    CBUUID(string: "0x2B47") : "High Resolution Height",
    CBUUID(string: "0x2B48") : "Middle Name",
    CBUUID(string: "0x2B49") : "Stride Length",
    CBUUID(string: "0x2B4A") : "Handedness",
    CBUUID(string: "0x2B4B") : "Device Wearing Position",
    CBUUID(string: "0x2B4C") : "Four Zone Heart Rate Limits",
    CBUUID(string: "0x2B4D") : "High Intensity Exercise Threshold",
    CBUUID(string: "0x2B4E") : "Activity Goal",
    CBUUID(string: "0x2B4F") : "Sedentary Interval Notification",
    CBUUID(string: "0x2B50") : "Caloric Intake",
    CBUUID(string: "0x2B51") : "TMAP Role",
    CBUUID(string: "0x2B77") : "Audio Input State",
    CBUUID(string: "0x2B78") : "Gain Settings Attribute",
    CBUUID(string: "0x2B79") : "Audio Input Type",
    CBUUID(string: "0x2B7A") : "Audio Input Status",
    CBUUID(string: "0x2B7B") : "Audio Input Control Point",
    CBUUID(string: "0x2B7C") : "Audio Input Description",
    CBUUID(string: "0x2B7D") : "Volume State",
    CBUUID(string: "0x2B7E") : "Volume Control Point",
    CBUUID(string: "0x2B7F") : "Volume Flags",
    CBUUID(string: "0x2B80") : "Volume Offset State",
    CBUUID(string: "0x2B81") : "Audio Location",
    CBUUID(string: "0x2B82") : "Volume Offset Control Point",
    CBUUID(string: "0x2B83") : "Audio Output Description",
    CBUUID(string: "0x2B84") : "Set Identity Resolving Key",
    CBUUID(string: "0x2B85") : "Coordinated Set Size",
    CBUUID(string: "0x2B86") : "Set Member Lock",
    CBUUID(string: "0x2B87") : "Set Member Rank",
    CBUUID(string: "0x2B88") : "Encrypted Data Key Material",
    CBUUID(string: "0x2B89") : "Apparent Energy 32",
    CBUUID(string: "0x2B8A") : "Apparent Power",
    CBUUID(string: "0x2B8B") : "Live Health Observations",
    CBUUID(string: "0x2B8C") : "CO₂ Concentration",
    CBUUID(string: "0x2B8D") : "Cosine of the Angle",
    CBUUID(string: "0x2B8E") : "Device Time Feature",
    CBUUID(string: "0x2B8F") : "Device Time Parameters",
    CBUUID(string: "0x2B90") : "Device Time",
    CBUUID(string: "0x2B91") : "Device Time Control Point",
    CBUUID(string: "0x2B92") : "Time Change Log Data",
    CBUUID(string: "0x2B93") : "Media Player Name",
    CBUUID(string: "0x2B94") : "Media Player Icon Object ID",
    CBUUID(string: "0x2B95") : "Media Player Icon URL",
    CBUUID(string: "0x2B96") : "Track Changed",
    CBUUID(string: "0x2B97") : "Track Title",
    CBUUID(string: "0x2B98") : "Track Duration",
    CBUUID(string: "0x2B99") : "Track Position",
    CBUUID(string: "0x2B9A") : "Playback Speed",
    CBUUID(string: "0x2B9B") : "Seeking Speed",
    CBUUID(string: "0x2B9C") : "Current Track Segments Object ID",
    CBUUID(string: "0x2B9D") : "Current Track Object ID",
    CBUUID(string: "0x2B9E") : "Next Track Object ID",
    CBUUID(string: "0x2B9F") : "Parent Group Object ID",
    CBUUID(string: "0x2BA0") : "Current Group Object ID",
    CBUUID(string: "0x2BA1") : "Playing Order",
    CBUUID(string: "0x2BA2") : "Playing Orders Supported",
    CBUUID(string: "0x2BA3") : "Media State",
    CBUUID(string: "0x2BA4") : "Media Control Point",
    CBUUID(string: "0x2BA5") : "Media Control Point Opcodes Supported",
    CBUUID(string: "0x2BA6") : "Search Results Object ID",
    CBUUID(string: "0x2BA7") : "Search Control Point",
    CBUUID(string: "0x2BA8") : "Energy 32",
    CBUUID(string: "0x2BA9") : "Media Player Icon Object Type",
    CBUUID(string: "0x2BAA") : "Track Segments Object Type",
    CBUUID(string: "0x2BAB") : "Track Object Type",
    CBUUID(string: "0x2BAC") : "Group Object Type",
    CBUUID(string: "0x2BAD") : "Constant Tone Extension Enable",
    CBUUID(string: "0x2BAE") : "Advertising Constant Tone Extension Minimum Length",
    CBUUID(string: "0x2BAF") : "Advertising Constant Tone Extension Minimum Transmit Count",
    CBUUID(string: "0x2BB0") : "Advertising Constant Tone Extension Transmit Duration",
    CBUUID(string: "0x2BB1") : "Advertising Constant Tone Extension Interval",
    CBUUID(string: "0x2BB2") : "Advertising Constant Tone Extension PHY",
    CBUUID(string: "0x2BB3") : "Bearer Provider Name",
    CBUUID(string: "0x2BB4") : "Bearer UCI",
    CBUUID(string: "0x2BB5") : "Bearer Technology",
    CBUUID(string: "0x2BB6") : "Bearer URI Schemes Supported List",
    CBUUID(string: "0x2BB7") : "Bearer Signal Strength",
    CBUUID(string: "0x2BB8") : "Bearer Signal Strength Reporting Interval",
    CBUUID(string: "0x2BB9") : "Bearer List Current Calls",
    CBUUID(string: "0x2BBA") : "Content Control ID",
    CBUUID(string: "0x2BBB") : "Status Flags",
    CBUUID(string: "0x2BBC") : "Incoming Call Target Bearer URI",
    CBUUID(string: "0x2BBD") : "Call State",
    CBUUID(string: "0x2BBE") : "Call Control Point",
    CBUUID(string: "0x2BBF") : "Call Control Point Optional Opcodes",
    CBUUID(string: "0x2BC0") : "Termination Reason",
    CBUUID(string: "0x2BC1") : "Incoming Call",
    CBUUID(string: "0x2BC2") : "Call Friendly Name",
    CBUUID(string: "0x2BC3") : "Mute",
    CBUUID(string: "0x2BC4") : "Sink ASE",
    CBUUID(string: "0x2BC5") : "Source ASE",
    CBUUID(string: "0x2BC6") : "ASE Control Point",
    CBUUID(string: "0x2BC7") : "Broadcast Audio Scan Control Point",
    CBUUID(string: "0x2BC8") : "Broadcast Receive State",
    CBUUID(string: "0x2BC9") : "Sink PAC",
    CBUUID(string: "0x2BCA") : "Sink Audio Locations",
    CBUUID(string: "0x2BCB") : "Source PAC",
    CBUUID(string: "0x2BCC") : "Source Audio Locations",
    CBUUID(string: "0x2BCD") : "Available Audio Contexts",
    CBUUID(string: "0x2BCE") : "Supported Audio Contexts",
    CBUUID(string: "0x2BCF") : "Ammonia Concentration",
    CBUUID(string: "0x2BD0") : "Carbon Monoxide Concentration",
    CBUUID(string: "0x2BD1") : "Methane Concentration",
    CBUUID(string: "0x2BD2") : "Nitrogen Dioxide Concentration",
    CBUUID(string: "0x2BD3") : "Non-Methane Volatile Organic Compounds Concentration",
    CBUUID(string: "0x2BD4") : "Ozone Concentration",
    CBUUID(string: "0x2BD5") : "Particulate Matter - PM1 Concentration",
    CBUUID(string: "0x2BD6") : "Particulate Matter - PM2.5 Concentration",
    CBUUID(string: "0x2BD7") : "Particulate Matter - PM10 Concentration",
    CBUUID(string: "0x2BD8") : "Sulfur Dioxide Concentration",
    CBUUID(string: "0x2BD9") : "Sulfur Hexafluoride Concentration",
    CBUUID(string: "0x2BDA") : "Hearing Aid Features",
    CBUUID(string: "0x2BDB") : "Hearing Aid Preset Control Point",
    CBUUID(string: "0x2BDC") : "Active Preset Index",
    CBUUID(string: "0x2BDD") : "Stored Health Observations",
    CBUUID(string: "0x2BDE") : "Fixed String 64",
    CBUUID(string: "0x2BDF") : "High Temperature",
    CBUUID(string: "0x2BE0") : "High Voltage",
    CBUUID(string: "0x2BE1") : "Light Distribution",
    CBUUID(string: "0x2BE2") : "Light Output",
    CBUUID(string: "0x2BE3") : "Light Source Type",
    CBUUID(string: "0x2BE4") : "Noise",
    CBUUID(string: "0x2BE5") : "Relative Runtime in a Correlated Color Temperature Range",
    CBUUID(string: "0x2BE6") : "Time Second 32",
    CBUUID(string: "0x2BE7") : "VOC Concentration",
    CBUUID(string: "0x2BE8") : "Voltage Frequency",
    CBUUID(string: "0x2BE9") : "Battery Critical Status",
    CBUUID(string: "0x2BEA") : "Battery Health Status",
    CBUUID(string: "0x2BEB") : "Battery Health Information",
    CBUUID(string: "0x2BEC") : "Battery Information",
    CBUUID(string: "0x2BED") : "Battery Level Status",
    CBUUID(string: "0x2BEE") : "Battery Time Status",
    CBUUID(string: "0x2BEF") : "Estimated Service Date",
    CBUUID(string: "0x2BF0") : "Battery Energy Status",
    CBUUID(string: "0x2BF1") : "Observation Schedule Changed",
    CBUUID(string: "0x2BF2") : "Current Elapsed Time",
    CBUUID(string: "0x2BF3") : "Health Sensor Features",
    CBUUID(string: "0x2BF4") : "GHS Control Point",
    CBUUID(string: "0x2BF5") : "LE GATT Security Levels",
    CBUUID(string: "0x2BF6") : "ESL Address",
    CBUUID(string: "0x2BF7") : "AP Sync Key Material",
    CBUUID(string: "0x2BF8") : "ESL Response Key Material",
    CBUUID(string: "0x2BF9") : "ESL Current Absolute Time",
    CBUUID(string: "0x2BFA") : "ESL Display Information",
    CBUUID(string: "0x2BFB") : "ESL Image Information",
    CBUUID(string: "0x2BFC") : "ESL Sensor Information",
    CBUUID(string: "0x2BFD") : "ESL LED Information",
    CBUUID(string: "0x2BFE") : "ESL Control Point",
    CBUUID(string: "0x2BFF") : "UDI for Medical Devices",
    CBUUID(string: "0x2C00") : "GMAP Role",
    CBUUID(string: "0x2C01") : "UGG Features",
    CBUUID(string: "0x2C02") : "UGT Features",
    CBUUID(string: "0x2C03") : "BGS Features",
    CBUUID(string: "0x2C04") : "BGR Features"
]
